apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-weather
  labels:
    app: golang-weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-weather
  template:
    metadata:
      labels:
        app: golang-weather
    spec:
      containers:
        - name: golang-weather
          image: ghcr.io/stefanprodan/podinfo:6.7.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9898
