apiVersion: v1
kind: Service
metadata:
  name: golang-weather
  labels:
    app: golang-weather
spec:
  type: LoadBalancer
  selector:
    app: golang-weather
  ports:
    - name: http
      port: 80          # external LB port
      targetPort: 9898  # MUST match containerPort
